/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as SettingsPasswordRouteImport } from './routes/settings_/password'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PostsPostIdEditRouteImport } from './routes/posts_.$postId.edit'
import { Route as Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125RouteImport } from './routes/{-$locale}.archive.{-$year}.{-$Date}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/settings_/password',
  path: '/settings/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/posts_/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route =
  Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125RouteImport.update(
    {
      id: '/{-$locale}/archive/{-$year}/{-$Date}',
      path: '/{-$locale}/archive/{-$year}/{-$Date}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}/{-$Date}': typeof Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/posts': typeof PostsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}/{-$Date}': typeof Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings_/password': typeof SettingsPasswordRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/posts_/$postId/edit': typeof PostsPostIdEditRoute
  '/{-$locale}/archive/{-$year}/{-$Date}': typeof Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/about'
    | '/posts/$postId'
    | '/settings/profile'
    | '/settings/password'
    | '/posts/'
    | '/products/'
    | '/posts/$postId/edit'
    | '/{-$locale}/archive/{-$year}/{-$Date}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/about'
    | '/posts/$postId'
    | '/settings/profile'
    | '/settings/password'
    | '/posts'
    | '/products'
    | '/posts/$postId/edit'
    | '/{-$locale}/archive/{-$year}/{-$Date}'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/about'
    | '/posts/$postId'
    | '/settings/profile'
    | '/settings_/password'
    | '/posts/'
    | '/products/'
    | '/posts_/$postId/edit'
    | '/{-$locale}/archive/{-$year}/{-$Date}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
  Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route: typeof Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/password': {
      id: '/settings_/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/edit': {
      id: '/posts_/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/archive/{-$year}/{-$Date}': {
      id: '/{-$locale}/archive/{-$year}/{-$Date}'
      path: '/{-$locale}/archive/{-$year}/{-$Date}'
      fullPath: '/{-$locale}/archive/{-$year}/{-$Date}'
      preLoaderRoute: typeof Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PostsPostIdEditRoute: PostsPostIdEditRoute,
  Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route:
    Char123LocaleChar125ArchiveChar123YearChar125Char123DateChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
